#pragma once

#include <string>

#define PONG_MASTER_VERSION           0.300
#define PONG_MASTER_VERSIONS          "0.3.0.0"
#define PONG_MASTER_VERSIONS_ANSI     "0.3.0.0"

#define PONG_MASTER_VERSION_STABLE    0
#define PONG_MASTER_VERSION_MAJOR     3
#define PONG_MASTER_VERSION_MINOR     0
#define PONG_MASTER_VERSION_PATCH     0

#define GAME_VERSION        PONG_MASTER_VERSION
#define GAME_VERSIONS       PONG_MASTER_VERSIONS
#define GAME_VERSIONS_ANSI  PONG_MASTER_VERSIONS_ANSI

