#pragma once

#include <string>

#define PONG_SERVER_VERSION           0.330
#define PONG_SERVER_VERSIONS          "0.3.3.0"
#define PONG_SERVER_VERSIONS_ANSI     "0.3.3.0"

#define PONG_SERVER_VERSION_STABLE    0
#define PONG_SERVER_VERSION_MAJOR     3
#define PONG_SERVER_VERSION_MINOR     3
#define PONG_SERVER_VERSION_PATCH     0

#define GAME_VERSION        PONG_SERVER_VERSION
#define GAME_VERSIONS       PONG_SERVER_VERSIONS
#define GAME_VERSIONS_ANSI  PONG_SERVER_VERSIONS_ANSI

